// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfD9P1ozBR9pYrPq1iyTJ_eKhyVNJREDc',
    appId: '1:994501797261:web:afeb1e73b209c8185149c4',
    messagingSenderId: '994501797261',
    projectId: 'qr-atten-sys',
    authDomain: 'qr-atten-sys.firebaseapp.com',
    storageBucket: 'qr-atten-sys.appspot.com',
    measurementId: 'G-DC13E71N3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0OvdrqwJDVBkgJmqde4EjXXokX0pyAJY',
    appId: '1:994501797261:android:25db2a614c8fb5965149c4',
    messagingSenderId: '994501797261',
    projectId: 'qr-atten-sys',
    storageBucket: 'qr-atten-sys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOJVSv4tkzWOGEM_CZf2CzHYynaeI4Lrw',
    appId: '1:994501797261:ios:fa0c2c03221404ef5149c4',
    messagingSenderId: '994501797261',
    projectId: 'qr-atten-sys',
    storageBucket: 'qr-atten-sys.appspot.com',
    iosBundleId: 'com.example.qrAttemdance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOJVSv4tkzWOGEM_CZf2CzHYynaeI4Lrw',
    appId: '1:994501797261:ios:fa0c2c03221404ef5149c4',
    messagingSenderId: '994501797261',
    projectId: 'qr-atten-sys',
    storageBucket: 'qr-atten-sys.appspot.com',
    iosBundleId: 'com.example.qrAttemdance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfD9P1ozBR9pYrPq1iyTJ_eKhyVNJREDc',
    appId: '1:994501797261:web:a08527f29a21a6e55149c4',
    messagingSenderId: '994501797261',
    projectId: 'qr-atten-sys',
    authDomain: 'qr-atten-sys.firebaseapp.com',
    storageBucket: 'qr-atten-sys.appspot.com',
    measurementId: 'G-K7PRWZBQXH',
  );
}
